#!/usr/bin/env ruby

require "bundler"
Bundler.require(:default)
Dotenv.load

require_relative "lib/render"

renderer = Render.new

prompt = "Use the python-mnemonic library to generate a mnemonic code in English for the phrase 'Heroku AI'"

request = <<~JSON
{
  "model": "#{ENV["INFERENCE_MODEL_ID"]}",
  "messages": [
    {
      "role": "user",
      "content": "#{prompt}"
    }
  ]
}
JSON

renderer.heroku_print("Here is the request we are sending to Heroku for inferencing...")

renderer.print_markdown(
  <<~MARKDOWN
  ```json
  #{request}
  ```
  MARKDOWN
)

answer = renderer.confirm("Ready to send the inference request?")
exit(0) unless answer

response = renderer.inference_request(request:, print_last_message: false)
renderer.print_large_box(response.dig("choices", 0, "message", "content"))

renderer.hr
