#!/usr/bin/env ruby

require "bundler"
Bundler.require(:default)
Dotenv.load

require_relative "lib/render"

renderer = Render.new

PROMPT = "How many leads were created last week?"

request = <<~JSON
{
  "model": "claude-3-5-sonnet",
  "messages": [
    {
      "role": "user",
      "content": "#{PROMPT}"
    }
  ],
  "tools": [
    {
      "type": "heroku_tool",
      "function": "database_get_schema",
      "runtime_params": {
        "target_app_name": "heroku-df24-trello",
        "tool_params": {
          "db_attachment": "DATABASE"
        }
      }
    },
    {
      "type": "heroku_tool",
      "function": "database_run_query",
      "runtime_params": {
        "target_app_name": "heroku-df24-trello",
        "tool_params": {
          "db_attachment": "DATABASE"
        }
      }
    }
  ],
  "tool_choice": "auto"
}
JSON

renderer.heroku_print("Here is the request we are sending to Heroku for inferencing...")

renderer.print_markdown(
  <<~MARKDOWN
  ```json
  #{request}
  ```
  MARKDOWN
)

answer = renderer.confirm("Ready to send the inference request?")
exit(0) unless answer

renderer.inference_request(request:)

renderer.hr
