#!/usr/bin/env ruby

require "bundler"
Bundler.require(:default)
Dotenv.load

require_relative "lib/render"

renderer = Render.new

prompt = "Take a random set of 3 leads (first name and last name) created in the last week and add them to my 'Reach Out' list in Trello."

request = <<~JSON
{
  "model": "claude-3-5-sonnet",
  "messages": [
    {
      "role": "user",
      "content": "#{prompt}"
    }
  ],
  "tools": [
    {
      "type": "heroku_tool",
      "function": "database_get_schema",
      "runtime_params": {
        "target_app_name": "heroku-df24-trello",
        "tool_params": {
          "db_attachment": "DATABASE"
        }
      }
    },
    {
      "type": "heroku_tool",
      "function": "database_run_query",
      "runtime_params": {
        "target_app_name": "heroku-df24-trello",
        "tool_params": {
          "db_attachment": "DATABASE"
        }
      }
    },
    {
      "type": "heroku_tool",
      "function": "dyno_run_command",
      "runtime_params": {
        "target_app_name": "heroku-df24-trello",
        "tool_params": {
          "cmd": "leads_to_trello"
        }
      },
      "description": "This tool is able to create Trello cards in the Reach Out list.",
      "parameters": {
        "type": "object",
        "properties": {
          "lead_names": {
            "type": "string",
            "description": "A comma-separated list of lead names to add as Trello cards."
          }
        },
        "required": ["content"]
      }
    }
  ],
  "tool_choice": "auto"
}
JSON

renderer.heroku_print("Here is the request we are sending to Heroku for inferencing...")

renderer.print_markdown(
  <<~MARKDOWN
  ```json
  #{request}
  ```
  MARKDOWN
)

answer = renderer.confirm("Ready to send the inference request?")
exit(0) unless answer

renderer.inference_request(request:)
