#!/usr/bin/env ruby

require "bundler"
Bundler.require(:default)
Dotenv.load

require_relative "lib/render"

renderer = Render.new

request = <<~JSON
{
  "model": "claude-3-5-sonnet",
  "messages": [
    {
      "role": "user",
      "content": "Who won the Formula 1 2024 Belgian Grand Prix?"
    }
  ]
}
JSON

renderer.heroku_print("Here is the request we are sending to Heroku for inferencing...")

renderer.print_markdown(
  <<~MARKDOWN
  ```json
  #{request}
  ```
  MARKDOWN
)

answer = renderer.confirm("Ready to send the inference request?")
exit(0) unless answer

renderer.inference_request(request:)
